'use strict';
(() => {
const T=window.THREE,$=id=>document.getElementById(id);
const presenters=['Kelvin','Manuel','Bernardes','Vinícius','Manuel','Murylo'];
const shortIntros=['Pele e mucosas bloqueiam invasores. A defesa inata reage quando eles entram.','Vasos recolhem a linfa. Linfonodos ajudam a reconhecer ameaças e organizar a defesa.','Medula e timo formam e amadurecem células. Linfonodos e baço organizam respostas.','Linfócitos B produzem anticorpos; T coordenam a defesa e eliminam células infectadas.','A linfa conecta tecidos e linfonodos. O sangue distribui células da defesa.','Vacinas estimulam memória. Outros animais usam diferentes estratégias de proteção.'];
const content=[
{name:'Origens & inata',title:'O corpo.<br><em>A primeira fortaleza.</em>',intro:'Milhões de anos de evolução deram origem a uma defesa em camadas. A viagem começa na superfície — e segue até as células que reconhecem uma invasão.',topics:[
['Evolução','Uma história de sobrevivência','A seleção natural favoreceu mecanismos de defesa. A imunidade inata é antiga; a adaptativa surgiu na evolução dos vertebrados. Saneamento, nutrição e vacinação ajudaram a reduzir doenças ao longo da história.','body','skin'],
['Barreiras','1ª linha: impedir a entrada','Pele intacta e mucosas formam barreiras. Muco, cílios, acidez e substâncias antimicrobianas ajudam a bloquear invasores; a microbiota também participa da proteção.','body','skin'],
['Inflamação','2ª linha: reconhecer e recrutar','Se a barreira é rompida, mediadores aumentam o fluxo e a permeabilidade dos vasos. Neutrófilos e macrófagos alcançam o tecido e podem fagocitar invasores. Calor, rubor, edema e dor podem acompanhar a resposta.','micro','lymph']]},
{name:'Rede linfática',title:'Uma rede.<br><em>Por dentro de você.</em>',intro:'Removemos a camada externa para revelar os caminhos da linfa. A rede recolhe líquido dos tecidos, transporta informação e devolve esse líquido ao sangue.',topics:[
['A linfa','Do tecido para o vaso','O líquido que sai dos capilares sanguíneos ocupa espaços entre células. Ao entrar nos capilares linfáticos, passa a ser linfa: água, sais, proteínas e células, especialmente linfócitos. No intestino, também transporta gorduras.','body','lymph'],
['Vasos','Um fluxo de mão única','Capilares de fundo cego coletam líquido. Vasos com válvulas ajudam a evitar refluxo. Movimentos musculares, respiração e contrações dos vasos impulsionam a linfa, sem uma bomba central como o coração.','body','lymph'],
['Retorno ao sangue','O circuito se fecha','O ducto torácico drena a maior parte do corpo; o ducto linfático direito drena, em geral, o quadrante superior direito. A linfa retorna perto da junção das veias jugular interna e subclávia.','body','lymph']]},
{name:'Órgãos linfoides',title:'Onde a defesa<br><em>se organiza.</em>',intro:'Produzir, amadurecer e encontrar ameaças: cada órgão participa de uma etapa. Aproximamos o corpo para enxergar os pontos dessa rede.',topics:[
['Medula & timo','Órgãos primários: formação e maturação','A medula óssea produz células sanguíneas e é local de maturação dos B. Precursores dos T chegam ao timo, onde amadurecem e passam por seleção, ajudando a reduzir respostas contra o próprio corpo.','organs','lymph'],
['Linfonodo','Dentro de um ponto de encontro','Linfa entra por vasos aferentes e sai por eferentes. Antígenos e células apresentadoras encontram linfócitos B e T. O linfonodo filtra a linfa e organiza a ativação da resposta adaptativa.','node','lymph'],
['Baço & tonsilas','Órgãos secundários: vigilância','Linfonodos monitoram a linfa; o baço monitora o sangue e remove hemácias envelhecidas. Tonsilas, também chamadas amígdalas, participam da defesa nas entradas das vias respiratória e digestiva.','organs','lymph']]},
{name:'Adaptativa',title:'Do encontro<br><em>à resposta específica.</em>',intro:'Entramos no ambiente celular. Aqui, reconhecer o alvo certo muda a defesa: linfócitos B e T atuam de maneiras diferentes e podem formar memória.',topics:[
['Linfócitos B','Imunidade humoral','Após ativação, parte dos B se diferencia em plasmócitos, que secretam anticorpos. Eles se ligam a antígenos específicos e podem neutralizar ameaças, marcar alvos e ativar o complemento.','micro','lymph'],
['Linfócitos T','Coordenar e eliminar células infectadas','T auxiliares, geralmente CD4+, coordenam e ajudam outras células. T citotóxicos, geralmente CD8+, reconhecem fragmentos de antígenos apresentados por MHC e eliminam células infectadas.','micro','lymph'],
['Memória','O próximo encontro pode ser diferente','Células de memória podem responder de forma mais rápida e eficiente ao mesmo antígeno. A duração da proteção varia; plasmócitos de longa vida também podem manter anticorpos.','micro','lymph']]},
{name:'Integração',title:'Tudo conectado.<br><em>Uma defesa em movimento.</em>',intro:'O corpo que vimos por fora e as células que vimos por dentro pertencem ao mesmo circuito. A linfa transporta informação; o sangue ajuda a distribuir a resposta.',topics:[
['Tecido → linfonodo','A informação viaja','Antígenos podem drenar na linfa. Células dendríticas capturam material no tecido e migram por vasos linfáticos até o linfonodo, onde apresentam antígenos aos T. A resposta inata se conecta à adaptativa.','body','lymph'],
['Encontro','A mensagem ativa a defesa','O reconhecimento adequado, acompanhado dos sinais necessários, pode ativar linfócitos. Eles se multiplicam e geram células efetoras e de memória. A linfa não só drena: ela ajuda a conectar ameaça e resposta.','node','lymph'],
['Recirculação','Sangue → órgão linfoide → linfa → sangue','Linfócitos circulam entre esses compartimentos. Efetores podem chegar ao tecido inflamado pelo sangue. Nem todo leucócito segue o mesmo caminho: neutrófilos, por exemplo, são recrutados do sangue diretamente ao tecido.','body','lymph']]},
{name:'Saúde & espécies',title:'Proteger também<br><em>é aprender.</em>',intro:'A defesa precisa de equilíbrio. Vacinas exploram a memória; doenças revelam falhas de regulação. Em outros animais, a mesma necessidade levou a estratégias diferentes.',topics:[
['Disfunções','Quando a resposta erra ou enfraquece','Alergias respondem a substâncias geralmente inofensivas. Autoimunidade atinge componentes do próprio corpo. O HIV infecta, entre outras células, T CD4+ e pode comprometer a defesa; tratamento pode controlar a infecção.','micro','lymph'],
['Vacinas','Memória sem exigir a doença','Vacinas apresentam antígenos, ou instruções para produzi-los, estimulando proteção e memória. Doses e reforços dependem da vacina. A proteção e os efeitos sobre transmissão variam conforme o agente e a vacina.','micro','lymph'],
['Outras espécies','Adaptações diferentes, mesma necessidade','Mamíferos, peixes, anfíbios e répteis compartilham mecanismos inatos e adaptativos, com diferenças de órgãos e respostas. Insetos não têm B, T e anticorpos como os nossos. Compare os grupos na cena ao lado.','body','lymph']]}
];
const animalInfo=[['Mamíferos','B e T, anticorpos e órgãos especializados. A rede de linfonodos é bem desenvolvida.'],['Peixes','Peixes com mandíbula têm B, T e anticorpos. Em muitos peixes ósseos, o rim anterior é importante para produzir células sanguíneas.'],['Insetos','Hemócitos, fagocitose e peptídeos antimicrobianos. Sem B, T e anticorpos como os nossos; há formas de priming imune.'],['Anfíbios','Imunidade inata e adaptativa; pele com defesas próprias. Metamorfose e temperatura influenciam a resposta.'],['Répteis','B, T e anticorpos, com organização diferente. A temperatura ambiental influencia a resposta; a rede de linfonodos não é como a dos mamíferos.']];
let renderer;
try{renderer=new T.WebGLRenderer({canvas:$('world'),antialias:true,alpha:false,powerPreference:'high-performance'})}catch(e){$('loader').classList.add('hide');$('error').hidden=false;$('error').textContent='Não foi possível iniciar o 3D. Abra em um navegador com WebGL habilitado, como Chrome ou Edge, e ative a aceleração gráfica. '+e.message;return}
renderer.setPixelRatio(Math.min(devicePixelRatio,innerWidth<=640?1.25:1.75));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;
const scene=new T.Scene();scene.background=new T.Color(0x061311);scene.fog=new T.FogExp2(0x061311,.028);
const camera=new T.PerspectiveCamera(36,innerWidth/innerHeight,.05,80);scene.add(new T.HemisphereLight(0xdbeadb,0x182723,2.5));
const key=new T.DirectionalLight(0xf4e6ce,3.0);key.position.set(-3,4,5);scene.add(key);const rim=new T.DirectionalLight(0x79cbbb,3.4);rim.position.set(3,1,-4);scene.add(rim);const fill=new T.DirectionalLight(0xb1d0be,1);fill.position.set(1,-2,4);scene.add(fill);
const body=new T.Group(),skin=new T.Group(),muscles=new T.Group(),lymph=new T.Group(),organs=new T.Group(),node=new T.Group(),micro=new T.Group();body.add(muscles,skin,lymph,organs);body.position.x=1.25;node.position.x=1.25;micro.position.x=1.25;scene.add(body,node,micro);
const mat=(color,extra={})=>new T.MeshStandardMaterial({color,roughness:.6,metalness:0,...extra});
const skinMat=mat(0xc9c6ad,{transparent:true,opacity:1}),muscleMat=mat(0xb27771,{transparent:true,opacity:1}),lymphMat=mat(0xaed99b,{emissive:0x4b9d70,emissiveIntensity:.38}),organMat=mat(0xd99288,{emissive:0x4b1618,emissiveIntensity:.15});
const skinMeshes=[],muscleMeshes=[],flowPaths=[],flowDots=[],labels=[],floaters=[];
// Keep only the rear half of the external shell in lymphatic view.
renderer.localClippingEnabled=true;
const rearCut=new T.Plane(new T.Vector3(0,0,-1),0);
skinMat.side=T.DoubleSide;
lymphMat.emissiveIntensity=.65;
const v=a=>new T.Vector3(...a);
function mesh(g,m,parent,pos=[0,0,0],scale=[1,1,1]){const o=new T.Mesh(g,m);o.position.set(...pos);o.scale.set(...scale);parent.add(o);return o}
function ellipsoid(parent,pos,radii,material){return mesh(new T.SphereGeometry(1,32,24),material,parent,pos,radii)}
function tube(points,r=.018,material=lymphMat,parent=lymph,flow=false){const c=new T.CatmullRomCurve3(points.map(v));const o=mesh(new T.TubeGeometry(c,Math.max(24,points.length*14),r,8,false),material,parent);if(flow)flowPaths.push({curve:c,parent});return o}
function realSkin(){const data=window.SKIN_DATA;if(!data)throw Error('Camada de pele ausente');const bytes=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));const p=bytes(data.positions),idx=bytes(data.indices),g=new T.BufferGeometry();g.setAttribute('position',new T.BufferAttribute(new Float32Array(p.buffer),3));g.setIndex(new T.BufferAttribute(new Uint32Array(idx.buffer),1));g.computeVertexNormals();const o=mesh(g,skinMat,skin);g.computeBoundingBox();const size=g.boundingBox.getSize(new T.Vector3()),center=g.boundingBox.getCenter(new T.Vector3());o.scale.setScalar(4.8/size.y);o.position.copy(center).multiplyScalar(-4.8/size.y);skinMeshes.push(o);window.SKIN_DATA=null;}
function parseAnatomy(base64){const binary=Uint8Array.from(atob(base64),c=>c.charCodeAt(0)),view=new DataView(binary.buffer);if(view.getUint32(0,true)!==0x46546c67)throw Error('Modelo GLB inválido');let json,bin;for(let offset=12;offset<binary.length;){const length=view.getUint32(offset,true),type=view.getUint32(offset+4,true);if(type===0x4e4f534a)json=JSON.parse(new TextDecoder().decode(binary.subarray(offset+8,offset+8+length)));if(type===0x004e4942)bin=binary.subarray(offset+8,offset+8+length);offset+=8+length}if(!json||!bin)throw Error('Modelo incompleto');
function accessor(i){const a=json.accessors[i],bv=json.bufferViews[a.bufferView],constructors={5126:Float32Array,5125:Uint32Array,5123:Uint16Array,5121:Uint8Array},C=constructors[a.componentType],item={SCALAR:1,VEC2:2,VEC3:3,VEC4:4}[a.type];if(!C||(bv.byteStride&&bv.byteStride!==C.BYTES_PER_ELEMENT*item)||a.sparse)throw Error('Formato de anatomia não suportado');const start=bin.byteOffset+(bv.byteOffset||0)+(a.byteOffset||0);return new T.BufferAttribute(new C(binary.buffer,start,a.count*item),item)}
const raw=new T.Group();for(const n of json.nodes){if(n.mesh===undefined)continue;for(const p of json.meshes[n.mesh].primitives){const geometry=new T.BufferGeometry();geometry.setAttribute('position',accessor(p.attributes.POSITION));if(p.indices!==undefined)geometry.setIndex(accessor(p.indices));if(p.attributes.NORMAL!==undefined)geometry.setAttribute('normal',accessor(p.attributes.NORMAL));else geometry.computeVertexNormals();const o=new T.Mesh(geometry,muscleMat);o.name=n.name;raw.add(o);muscleMeshes.push(o)}}raw.rotation.x=-Math.PI/2;raw.updateMatrixWorld(true);const bounds=new T.Box3().setFromObject(raw),size=bounds.getSize(new T.Vector3());raw.scale.setScalar(4.8/size.y);raw.updateMatrixWorld(true);const center=new T.Box3().setFromObject(raw).getCenter(new T.Vector3());raw.position.sub(center);muscles.add(raw);return raw}
function buildLymph(){
tube([[.12,-.32,.12],[.08,.2,.12],[.04,.75,.11],[.02,1.1,.10],[.20,1.29,.06]],.023,lymphMat,lymph,true);
for(const s of [-1,1]){tube([[s*.25,-2.17,.09],[s*.27,-1.6,.15],[s*.3,-1.04,.18],[s*.25,-.40,.18],[s*.12,-.32,.12]],.013,lymphMat,lymph,true);tube([[s*.83,-.24,.12],[s*.74,.22,.16],[s*.64,.70,.15],[s*.47,1.04,.19],[s*.24,1.20,.19],[s*.15,1.30,.09]],.012,lymphMat,lymph,true);tube([[s*.14,1.78,.10],[s*.12,1.6,.12],[s*.16,1.3,.11]],.012,lymphMat,lymph,true);
for(let i=0;i<6;i++){const y=-.1+i*.18;tube([[s*.34,y,.23],[s*.20,y+.08,.27],[.05,y+.11,.14]],.008);tube([[s*.3,-1.8+i*.18,.14],[s*.39,-1.72+i*.18,.13]],.006)}
for(const p of [[s*.16,1.48,.13],[s*.16,1.35,.16],[s*.49,.98,.17],[s*.52,.91,.17],[s*.44,.91,.24],[s*.26,-.35,.21],[s*.3,-.43,.21],[s*.22,-.43,.21]]){const o=ellipsoid(lymph,p,[.032,.046,.027],lymphMat);o.rotation.z=s*.5}}
ellipsoid(lymph,[.12,-.32,.12],[.045,.075,.035],lymphMat);
for(const path of flowPaths){for(let i=0;i<4;i++){const dot=ellipsoid(path.parent,[0,0,0],[.014,.014,.014],new T.MeshBasicMaterial({color:0xe3f5b2}));flowDots.push({dot,curve:path.curve,phase:i/4})}}
}
const markers={timo:[0,.99,.11],baco:[.31,.30,.12],tonsilas:[.12,1.71,.13],medula:[-.28,-.79,.14],linfonodo:[-.49,.98,.17]};
function buildOrgans(){ellipsoid(organs,markers.timo,[.11,.14,.05],organMat);ellipsoid(organs,[.08,1.0,.10],[.07,.14,.05],organMat);const spleen=ellipsoid(organs,markers.baco,[.08,.17,.065],organMat);spleen.rotation.z=-.45;for(const s of [-1,1])ellipsoid(organs,[s*.12,1.71,.13],[.034,.05,.026],organMat);tube([[-.28,-.56,.10],[-.28,-.80,.13],[-.29,-1.02,.14]],.037,mat(0xe3c591),organs);}
function blob(radius,detail=3,seed=0){const g=new T.IcosahedronGeometry(radius,detail),p=g.attributes.position;for(let i=0;i<p.count;i++){const x=p.getX(i),y=p.getY(i),z=p.getZ(i),f=1+.055*Math.sin(x*8+seed)*Math.sin(y*7-seed)*Math.cos(z*6);p.setXYZ(i,x*f,y*f,z*f)}return g}
const nodeShell=mat(0x97b875,{transparent:true,opacity:.30,side:T.DoubleSide,depthWrite:false});
function buildNode(){const shell=mesh(blob(1.1,4),nodeShell,node,[0,0,0],[1.12,.85,.72]);shell.rotation.z=.25;const inner=mesh(blob(.88,3),mat(0x725a69,{transparent:true,opacity:.25,depthWrite:false}),node,[0,0,0],[1.07,.85,.73]);for(let i=0;i<7;i++){const a=i/7*Math.PI*2;ellipsoid(node,[Math.cos(a)*.75,Math.sin(a)*.56,.06],[.19,.17,.17],mat(0xaed99b,{transparent:true,opacity:.65}))}for(let i=0;i<18;i++){const a=i*2.399,r=.62*Math.sqrt((i+.5)/18);const o=mesh(blob(.055,1,i),mat(i%3?0xbbd6ae:0xd4949d),node,[Math.cos(a)*r,Math.sin(a)*r*.8,Math.sin(i)*.25]);floaters.push({o,base:o.position.clone(),speed:.6,phase:i})}tube([[-2.0,.8,0],[-1.55,.65,0],[-.93,.42,0]],.065,lymphMat,node,true);tube([[-2.0,-.65,0],[-1.5,-.47,0],[-1.0,-.32,0]],.065,lymphMat,node,true);tube([[.85,-.08,0],[1.4,-.1,0],[1.9,-.3,0]],.085,lymphMat,node,true);for(const path of flowPaths.filter(p=>p.parent===node)){for(let i=0;i<4;i++){const dot=ellipsoid(node,[0,0,0],[.035,.035,.035],mat(0xe6edae));flowDots.push({dot,curve:path.curve,phase:i/4})}}}
function cell(pos,r,color,name){const group=new T.Group();group.position.set(...pos);group.name=name;mesh(blob(r,4,pos[0]),mat(color,{transparent:true,opacity:.78,depthWrite:false}),group);mesh(blob(r*.36,3),mat(0x2e4c50),group,[r*.1,0,r*.15],[1,.75,1]);for(let i=0;i<14;i++){const a=i*2.399;ellipsoid(group,[Math.cos(a)*r*.65,Math.sin(a)*r*.65,Math.sin(i*4)*r*.4],[r*.04,r*.06,r*.035],mat(0xd7dec6))}micro.add(group);floaters.push({o:group,base:group.position.clone(),speed:.7,phase:pos[0]*3});return group}
const microCells={},antibodies=new T.Group(),invader=new T.Group();
function buildMicro(){microCells.b=cell([-.74,.30,0],.52,0x91b9bd,'B');microCells.t=cell([.68,.15,-.18],.46,0xb3cc8f,'T');microCells.macro=cell([-.36,-.47,-.12],.67,0x91b8a0,'Macrófago');microCells.target=cell([1.1,-.57,-.30],.55,0xb78489,'Célula infectada');for(let i=0;i<8;i++){const a=i/8*Math.PI*2;ellipsoid(microCells.macro,[Math.cos(a)*.55,Math.sin(a)*.55,0],[.17,.13,.18],mat(0x91b8a0))}
mesh(blob(.27,3),mat(0xd78686),invader);for(let i=0;i<24;i++){const y=1-(i+.5)/24*2,a=i*2.399,d=new T.Vector3(Math.cos(a)*Math.sqrt(1-y*y),y,Math.sin(a)*Math.sqrt(1-y*y));const spike=mesh(new T.ConeGeometry(.027,.12,8),mat(0xd78686),invader);spike.position.copy(d.clone().multiplyScalar(.31));spike.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),d)}invader.position.set(.10,.4,.25);micro.add(invader);
for(let i=0;i<10;i++){const g=new T.Group();tube([[0,-.12,0],[0,0,0],[-.09,.10,0]],.017,mat(0xe1edb3),g);tube([[0,0,0],[.09,.1,0]],.017,mat(0xe1edb3),g);const a=i/10*Math.PI*2;g.position.set(.10+Math.cos(a)*.52,.4+Math.sin(a)*.48,.3+Math.cos(i)*.15);g.rotation.z=-a;antibodies.add(g)}micro.add(antibodies);
const particles=new T.BufferGeometry(),positions=[];for(let i=0;i<100;i++){const a=i*2.399;positions.push(Math.cos(a)*3,Math.sin(a)*2,-1.5-(i%10)*.25)}particles.setAttribute('position',new T.Float32BufferAttribute(positions,3));micro.add(new T.Points(particles,new T.PointsMaterial({size:.035,color:0x8fb39f,transparent:true,opacity:.3})));}
function label(name,position,parent){const el=document.createElement('span');el.className='label';el.textContent=name;$('labels').append(el);labels.push({el,point:v(position),parent,name})}
let chapter=0,topic=0,animal=0,layer='skin',mode='body',activeMode='body',transition=null,frame=0,drag=null,userRotation=0,userZoom=0,loaded=false;
const target=new T.Vector3(),cameraGoal=new T.Vector3(),targetGoal=new T.Vector3();
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const views={body:{camera:[0,.05,9.5],target:[0,.05,0],rotation:.08},organs:{camera:[.1,.65,5.8],target:[.1,.65,0],rotation:-.12},node:{camera:[0,0,6.7],target:[0,0,0],rotation:-.12},micro:{camera:[0,0,6.5],target:[0,0,0],rotation:0}};
function visibility(m){activeMode=m;body.visible=m==='body'||m==='organs';node.visible=m==='node';micro.visible=m==='micro';$('layerTools').hidden=!body.visible;const config=views[m];cameraGoal.set(...config.camera);targetGoal.set(...config.target);if(innerWidth<=640){cameraGoal.x=1.25;targetGoal.x=1.25;cameraGoal.z=m==='body'?8.8:m==='organs'?6.5:7.2}body.rotation.y=config.rotation;node.rotation.y=config.rotation;userRotation=0;userZoom=0;updateMicro();}
function setView(m,instant=false){mode=m;const fromMode=activeMode;if(instant||!loaded||reduced){transition=null;visibility(m);camera.position.copy(cameraGoal);target.copy(targetGoal);camera.lookAt(target);$('travel').style.opacity=0;return}const entry=(m==='node'||m==='micro')&&m!==fromMode;transition={start:performance.now(),duration:entry?1900:1100,from:camera.position.clone(),look:target.clone(),mode:m,entry,switched:false};if(!entry)visibility(m);}
function updateMicro(){if(chapter===0){microCells.macro.visible=true;microCells.b.visible=false;microCells.t.visible=false;microCells.target.visible=true;antibodies.visible=false}else{microCells.macro.visible=false;microCells.b.visible=chapter===3?topic!==1:true;microCells.t.visible=chapter===3?topic!==0:true;microCells.target.visible=chapter===3&&topic===1||chapter===5&&topic===0;antibodies.visible=!(chapter===3&&topic===1)}invader.visible=true}
function applyLayer(name){layer=name;document.querySelectorAll('[data-layer]').forEach(b=>{b.classList.toggle('active',b.dataset.layer===name);b.setAttribute('aria-pressed',String(b.dataset.layer===name))});}

const speciesPanel=document.createElement('section');speciesPanel.id='speciesComparison';speciesPanel.hidden=true;speciesPanel.setAttribute('aria-label','Comparação visual da defesa entre espécies');document.body.prepend(speciesPanel);
const speciesShapes=["<path d=\"M36 126Q30 93 65 92L119 92L140 65L158 72L174 103L152 116L139 143L143 205H127L119 149H72L61 205H46L49 142L30 132L16 103L24 98Z\"/>","<path d=\"M27 120Q89 58 153 115L183 88L179 147L153 129Q88 189 27 120Z\"/><circle cx=\"49\" cy=\"115\" r=\"4\" fill=\"#061311\"/><path d=\"M91 85L115 60L128 89M86 152L113 179L125 149\"/>","<ellipse cx=\"100\" cy=\"143\" rx=\"27\" ry=\"47\"/><ellipse cx=\"100\" cy=\"92\" rx=\"22\" ry=\"25\"/><circle cx=\"100\" cy=\"61\" r=\"17\"/><path d=\"M86 49L73 27M114 49L127 27M77 95L43 73L25 88M76 120L37 118L18 143M76 153L43 174L33 205M123 95L157 73L175 88M124 120L163 118L182 143M124 153L157 174L167 205\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"7\"/>","<path d=\"M54 127Q43 86 67 76Q78 59 92 76H108Q124 59 134 76Q158 94 147 127L176 160L160 181L137 150L143 202L119 202L111 164H89L81 202H57L63 150L40 181L24 160Z\"/><circle cx=\"77\" cy=\"82\" r=\"5\" fill=\"#061311\"/><circle cx=\"123\" cy=\"82\" r=\"5\" fill=\"#061311\"/>","<path d=\"M20 181Q45 125 79 114L119 102L145 75L176 82L187 103L158 115L134 133L137 160L160 185L148 196L121 171L112 145L88 149L71 181L46 197L37 185L60 164L65 140Q40 149 20 181Z\"/>"],humanShape="<circle cx=\"100\" cy=\"34\" r=\"19\"/><path d=\"M80 60Q100 53 120 60L139 130L126 135L114 93L115 154L126 225L109 225L100 165L91 225L74 225L85 154L86 93L74 135L61 130Z\"/>",speciesDifferences=[["Mesmo plano de defesa","Mamíferos, como nós, têm linfonodos, linfócitos B e T e anticorpos."],["Outro centro de produção","Em muitos peixes ósseos, o rim anterior tem papel importante na produção de células sanguíneas."],["Defesa sem B e T","Hemócitos e peptídeos antimicrobianos atuam na defesa. Não há anticorpos como os humanos."],["A pele também protege","Defesas da pele, metamorfose e temperatura influenciam a resposta imune."],["Organização diferente","Têm B, T e anticorpos; a rede de linfonodos difere da dos mamíferos."]];
const speciesOverlays=["<g stroke=\"#d6ec9c\" stroke-width=\"2\" fill=\"none\"><path d=\"M57 115H131L150 95M60 115L54 179M129 115L135 179\"/></g><g fill=\"#d6ec9c\"><circle cx=\"60\" cy=\"115\" r=\"5\"/><circle cx=\"129\" cy=\"115\" r=\"5\"/><circle cx=\"144\" cy=\"103\" r=\"4\"/></g>","<path d=\"M67 105Q98 91 126 108\" stroke=\"#d99288\" stroke-width=\"9\" fill=\"none\"/><text x=\"100\" y=\"218\" text-anchor=\"middle\">Rim anterior</text>","<g fill=\"#d6ec9c\"><circle cx=\"94\" cy=\"98\" r=\"5\"/><circle cx=\"108\" cy=\"126\" r=\"5\"/><circle cx=\"91\" cy=\"145\" r=\"5\"/><circle cx=\"103\" cy=\"165\" r=\"5\"/></g><text x=\"100\" y=\"233\" text-anchor=\"middle\">Hemócitos</text>","<path d=\"M54 127Q43 86 67 76Q78 59 92 76H108Q124 59 134 76Q158 94 147 127\" stroke=\"#d6ec9c\" stroke-width=\"4\" fill=\"none\"/><g fill=\"#d99288\"><circle cx=\"91\" cy=\"120\" r=\"7\"/><circle cx=\"110\" cy=\"135\" r=\"7\"/></g><text x=\"100\" y=\"233\" text-anchor=\"middle\">Pele + B e T</text>","<g fill=\"#d99288\"><circle cx=\"91\" cy=\"130\" r=\"7\"/><circle cx=\"114\" cy=\"120\" r=\"7\"/></g><path d=\"M96 90V102M96 94L89 87M96 94L103 87\" stroke=\"#d6ec9c\" stroke-width=\"3\" fill=\"none\"/><text x=\"100\" y=\"233\" text-anchor=\"middle\">B, T e anticorpos</text>"];
function speciesFigure(shape,human=false){return '<svg viewBox="0 0 200 240" role="img" aria-label="'+(human?'Ser humano: rede de linfonodos':'Silhueta ilustrativa do grupo selecionado')+'"><g fill="currentColor" opacity=".38">'+shape+'</g>'+(human?'<g stroke="#d6ec9c" stroke-width="2" fill="none"><path d="M100 60V155M100 85L81 88L73 125M100 85L119 88L127 125M100 155L88 210M100 155L112 210"/></g><g fill="#d6ec9c">'+[[94,65],[106,65],[81,88],[119,88],[88,156],[112,156]].map(p=>'<circle cx="'+p[0]+'" cy="'+p[1]+'" r="5"/>').join('')+'</g>':speciesOverlays[animal])+'</svg>'}
function renderSpecies(){const comparing=chapter===5&&topic===2;speciesPanel.hidden=!comparing;document.body.classList.toggle('comparing',comparing);if(!comparing)return;const a=animalInfo[animal],d=speciesDifferences[animal];speciesPanel.innerHTML='<div class="comparison-heading"><span>ESTRATÉGIAS DE DEFESA</span><h2>Uma necessidade. Diferentes caminhos.</h2></div><div class="species-pair"><article>'+speciesFigure(humanShape,true)+'<h3>Ser humano</h3><p>Linfonodos · B e T · anticorpos</p></article><span class="versus">×</span><article>'+speciesFigure(speciesShapes[animal])+'<h3>'+a[0]+'</h3><p>'+d[0]+'</p></article></div><div class="species-select" role="group" aria-label="Escolher grupo animal">'+animalInfo.map((a,i)=>'<button class="option '+(i===animal?'active':'')+'" data-species="'+i+'" aria-pressed="'+(i===animal)+'">'+a[0]+'</button>').join('')+'</div><div class="comparison-note"><strong>'+d[0]+'</strong><p>'+d[1]+'</p></div><small>Silhuetas e rede esquemáticas, fora de escala. O ser humano também é um mamífero.</small>';document.querySelectorAll('[data-species]').forEach(b=>b.onclick=()=>{animal=Number(b.dataset.species);renderSpecies()});}

function extras(){renderSpecies();if(chapter===5&&topic===2){$('extra').innerHTML=''}else if(chapter===3&&topic===2||chapter===5&&topic===1){$('extra').innerHTML='<svg class="mini-chart" viewBox="0 0 380 95" role="img" aria-label="Curvas conceituais: a resposta secundária pode ser mais rápida e intensa"><path d="M20 10V70H365" fill="none" stroke="#789887"/><path d="M25 67Q65 67 80 49T125 67H170" fill="none" stroke="#7fc6b1" stroke-width="2"/><path d="M170 67C190 66 195 10 230 12S290 45 350 48" fill="none" stroke="#d6ec9c" stroke-width="2"/><text x="28" y="88">1º contato</text><text x="190" y="88">Com memória · curva sem escala</text></svg>'}else $('extra').innerHTML=''}
function renderUI(){const c=content[chapter],t=c.topics[topic];$('eyebrow').textContent=`${presenters[chapter].toUpperCase()} / ${c.name.toUpperCase()}`;$('title').innerHTML=c.title;$('intro').textContent=c.intro;$('mobileBrief').textContent=shortIntros[chapter];$('presenterSelect').innerHTML=content.map((a,i)=>`<option value="${i}" ${i===chapter?'selected':''}>${i+1}. ${presenters[i]} · ${a.name}</option>`).join('');$('readMore').setAttribute('aria-expanded','false');$('readMore').textContent='Saiba mais';document.body.classList.toggle('reading',false);$('detailTitle').textContent=t[1];$('detail').textContent=t[2];$('topics').innerHTML=c.topics.map((a,i)=>`<button class="${i===topic?'active':''}" data-topic="${i}" aria-pressed="${i===topic}">${a[0]}</button>`).join('');document.querySelectorAll('[data-topic]').forEach(b=>b.onclick=()=>selectTopic(Number(b.dataset.topic)));$('chapters').innerHTML=content.map((c,i)=>`<button class="${chapter===i?'active':''}" data-chapter="${i}" ${chapter===i?'aria-current="step"':''}><span>${presenters[i]}</span>${c.name}</button>`).join('');document.querySelectorAll('[data-chapter]').forEach(b=>b.onclick=()=>go(Number(b.dataset.chapter)));$('counter').textContent=`0${chapter+1} / 06`;$('prev').disabled=chapter===0;$('next').disabled=chapter===5;$('progress').style.width=`${(chapter+1)/6*100}%`;$('scale').textContent={body:'ESCALA / CORPO HUMANO',organs:'ESCALA / ÓRGÃOS',node:'ESCALA / LINFONODO',micro:'ESCALA / AMBIENTE CELULAR'}[t[3]];$('sceneCaption').textContent={body:'Anatomia real, camadas ilustrativas. Um corpo, vários níveis de defesa.',organs:'Órgãos primários e secundários. Posições esquemáticas.',node:'Corte ilustrativo do linfonodo. Linfa, antígenos e células se encontram.',micro:'Modelos celulares ilustrativos, fora de escala. Cores diferenciam funções.'}[t[3]];extras()}
function selectTopic(i){topic=Math.max(0,Math.min(content[chapter].topics.length-1,i));const t=content[chapter].topics[topic];renderUI();applyLayer(t[4]);setView(t[3]);updateMicro()}
function go(i,instant=false){chapter=Math.max(0,Math.min(5,i));topic=0;animal=0;const t=content[chapter].topics[0];history.replaceState(null,'',`#${chapter}`);renderUI();applyLayer(t[4]);setView(t[3],instant);updateMicro()}
$('readMore').onclick=()=>{const expanded=$('readMore').getAttribute('aria-expanded')!=='true';$('readMore').setAttribute('aria-expanded',String(expanded));$('readMore').textContent=expanded?'Menos texto':'Saiba mais';document.body.classList.toggle('reading',expanded)};$('presenterSelect').onchange=e=>go(Number(e.target.value));
document.querySelectorAll('[data-layer]').forEach(b=>b.onclick=()=>applyLayer(b.dataset.layer));$('prev').onclick=()=>go(chapter-1);$('next').onclick=()=>go(chapter+1);$('sourcesButton').onclick=()=>$('sources').showModal();$('closeSources').onclick=()=>$('sources').close();$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{}};
document.addEventListener('keydown',e=>{if($('sources').open)return;if(e.target.closest('button,a')&&[' ','Enter'].includes(e.key))return;if(['ArrowRight','PageDown',' '].includes(e.key)){e.preventDefault();go(chapter+1)}if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();go(chapter-1)}if(e.key.toLowerCase()==='f')$('fullscreen').click();if(e.key.toLowerCase()==='r')setView(mode);if(e.key==='Home')go(0);if(e.key==='End')go(5)});
const canvas=$('world');canvas.style.touchAction='pan-y';canvas.addEventListener('pointerdown',e=>{if(transition)return;drag={x:e.clientX,rotation:userRotation};canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(drag)userRotation=drag.rotation+(e.clientX-drag.x)*.006});canvas.addEventListener('pointerup',()=>drag=null);canvas.addEventListener('pointercancel',()=>drag=null);canvas.addEventListener('wheel',e=>{if(innerWidth<=640)return;e.preventDefault();if(!transition)userZoom=T.MathUtils.clamp(userZoom+e.deltaY*.003,-2.1,2.2)},{passive:false});
let width=innerWidth,height=innerHeight,rect;function resize(){width=innerWidth;height=innerWidth<=640?canvas.getBoundingClientRect().height:innerHeight;renderer.setSize(width,height,false);camera.aspect=width/height;camera.updateProjectionMatrix();rect=canvas.getBoundingClientRect();if(loaded)setView(mode,true)}window.addEventListener('resize',resize);window.addEventListener('scroll',()=>rect=canvas.getBoundingClientRect(),{passive:true});
const clock=new T.Clock(),projected=new T.Vector3(),worldPoint=new T.Vector3();
function opacity(group,value){group.visible=value>.01;group.traverse(o=>{if(o.isMesh){o.material.opacity=value;o.material.depthWrite=value>.95;o.material.transparent=value<.999}})}
function updateLabels(){for(const l of labels){let visible=l.parent.visible;if(l.parent===body)visible=body.visible&&layer==='lymph';if(l.parent===micro){const cellName=l.name;visible=micro.visible&&(cellName==='Macrófago'?microCells.macro.visible:cellName==='Linfócito B'?microCells.b.visible:cellName==='Linfócito T'?microCells.t.visible:cellName==='Célula infectada'?microCells.target.visible:cellName==='Anticorpos'?antibodies.visible:true)}if(innerWidth<=640&&l.name==='Antígeno / invasor')visible=false;if(!visible){l.el.hidden=true;continue}worldPoint.copy(l.point);l.parent.localToWorld(worldPoint);projected.copy(worldPoint).project(camera);if(projected.z>1||projected.z<-1||Math.abs(projected.x)>1||Math.abs(projected.y)>1){l.el.hidden=true;continue}const offsets={Timo:[60,-5],'Baço':[65,4],Tonsilas:[48,-10],'Medula óssea':[-65,0],Linfonodos:[-70,-12],'Ducto torácico':[65,2]};const off=l.parent===body?(offsets[l.name]||[0,0]):[0,0],small=innerWidth<=640?.6:1;const x=(projected.x*.5+.5)*width+off[0]*small,y=(-projected.y*.5+.5)*height+(rect?.top||0)+off[1]*small;if(innerWidth>640&&x<innerWidth*.43){l.el.hidden=true;continue}l.el.hidden=false;l.el.style.left=x+'px';l.el.style.top=y+'px'}}
let skinOpacity=1,muscleOpacity=0;
function animate(now){frame=requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.05),time=clock.elapsedTime;
if(transition){const a=transition,t=Math.min((now-a.start)/a.duration,1),ease=t*t*(3-2*t);if(a.entry){if(t<.5){const focus=activeMode==='body'||activeMode==='organs'?body.localToWorld(v(markers.linfonodo)):activeMode==='node'?node.position.clone():micro.position.clone();camera.position.lerpVectors(a.from,focus.clone().add(v([0,0,1.35])),Math.sin(t*Math.PI));target.lerpVectors(a.look,focus,Math.sin(t*Math.PI))}else{if(!a.switched){visibility(a.mode);a.switched=true}const u=(t-.5)*2,ee=u*u*(3-2*u);camera.position.lerpVectors(cameraGoal.clone().multiplyScalar(.56),cameraGoal,ee);target.copy(targetGoal)}$('travel').style.opacity=String(Math.sin(t*Math.PI)*.96)}else{camera.position.lerpVectors(a.from,cameraGoal,ease);target.lerpVectors(a.look,targetGoal,ease)}if(t>=1){transition=null;camera.position.copy(cameraGoal);target.copy(targetGoal);$('travel').style.opacity=0}}else{camera.position.lerp(cameraGoal.clone().add(v([0,0,userZoom])),1-Math.exp(-dt*5));target.lerp(targetGoal,1-Math.exp(-dt*5))}
camera.lookAt(target);const baseRotation=views[activeMode].rotation;body.rotation.y=T.MathUtils.damp(body.rotation.y,baseRotation+userRotation,5,dt);node.rotation.y=T.MathUtils.damp(node.rotation.y,baseRotation+userRotation,5,dt);micro.rotation.y=T.MathUtils.damp(micro.rotation.y,userRotation,5,dt);
skinMat.clippingPlanes=layer==='lymph'?[rearCut]:[];
rearCut.normal.set(0,0,-1).applyQuaternion(body.quaternion);rearCut.constant=-rearCut.normal.dot(body.position);
skinOpacity=T.MathUtils.damp(skinOpacity,layer==='skin'?1:layer==='lymph'?.10:0,4,dt);muscleOpacity=T.MathUtils.damp(muscleOpacity,layer==='anatomy'?1:0,4,dt);opacity(skin,skinOpacity);opacity(muscles,muscleOpacity);lymph.visible=layer==='lymph';organs.visible=layer==='lymph';
if(!reduced){for(const f of floaters){f.o.position.y=f.base.y+Math.sin(time*f.speed+f.phase)*.035;f.o.rotation.y=Math.sin(time*.2+f.phase)*.1}invader.rotation.y=time*.18;invader.rotation.z=Math.sin(time*.3)*.13;for(const d of flowDots)d.dot.position.copy(d.curve.getPoint((time*.12+d.phase)%1));antibodies.children.forEach((a,i)=>a.rotation.y=Math.sin(time*.3+i)*.3)}scene.updateMatrixWorld();updateLabels();if(chapter===5&&topic===2){for(const l of labels)l.el.hidden=true}renderer.render(scene,camera)}
async function init(){try{resize();realSkin();const raw=parseAnatomy(window.ANATOMY_BASE64);window.ANATOMY_BASE64=null;buildLymph();buildOrgans();buildNode();buildMicro();label('Timo',markers.timo,body);label('Baço',markers.baco,body);label('Tonsilas',markers.tonsilas,body);label('Medula óssea',markers.medula,body);label('Linfonodos',markers.linfonodo,body);label('Ducto torácico',[.06,.56,.16],body);label('Vasos aferentes',[-1.60,.84,0],node);label('Folículos B',[-.48,.66,0],node);label('Região de células T',[.03,-.17,.12],node);label('Vaso eferente',[1.53,-.34,0],node);label('Linfócito B',[-.74,.98,0],micro);label('Linfócito T',[.68,.79,0],micro);label('Macrófago',[-.36,-1.24,0],micro);label('Célula infectada',[1.1,-1.27,-.3],micro);label('Antígeno / invasor',[.08,.85,.3],micro);label('Anticorpos',[.18,-.2,.4],micro);
loaded=true;const initial=Number(location.hash.slice(1));go(Number.isInteger(initial)&&initial>=0&&initial<=5?initial:0,true);$('loadStatus').textContent='Anatomia pronta. Boa viagem.';requestAnimationFrame(()=>{$('loader').classList.add('hide');requestAnimationFrame(animate)});window.INSIDE_DEFENSE={body,muscles,skin,lymph,organs,node,micro,raw,content,go,selectTopic,getState:()=>({chapter,topic,mode,layer,activeMode}),dispose:()=>{cancelAnimationFrame(frame);renderer.dispose()}};
}catch(e){$('loader').classList.add('hide');$('error').hidden=false;$('error').textContent='O carregamento não foi concluído. Confira se vendor/three.offline.js e models/anatomy-data.js estão junto dos arquivos da apresentação. Detalhe: '+e.message;console.error(e)}}
window.addEventListener('hashchange',()=>{const n=Number(location.hash.slice(1));if(Number.isInteger(n)&&n>=0&&n<=5&&n!==chapter)go(n)});canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();cancelAnimationFrame(frame);$('error').hidden=false;$('error').textContent='A sessão gráfica foi interrompida. Recarregue a página para reiniciar o 3D.'});init();
})();






