const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const elements=new Map();function el(id){if(!elements.has(id))elements.set(id,{id,style:{},hidden:false,innerHTML:'',textContent:'',classList:{add(){}},append(){},setAttribute(){},addEventListener(){},getBoundingClientRect:()=>({top:0,left:0,width:1440,height:900}),showModal(){},close(){}});return elements.get(id)}
let now=0,callbacks=[];const context=vm.createContext({window:{addEventListener(){}},document:{body:{prepend(){},classList:{toggle(){}}},getElementById:el,querySelectorAll:()=>[],createElement:()=>el('label'+elements.size),addEventListener(){},documentElement:{}},console,performance:{now:()=>now},innerWidth:1440,innerHeight:900,devicePixelRatio:1,matchMedia:()=>({matches:false}),atob,TextDecoder,Uint8Array,Float32Array,Uint32Array,Uint16Array,DataView,location:{hash:''},history:{replaceState(){}},requestAnimationFrame:f=>(callbacks.push(f),1),cancelAnimationFrame(){}});
vm.runInContext(fs.readFileSync('vendor/three.offline.js','utf8'),context);context.window.THREE.WebGLRenderer=class{setPixelRatio(){}setSize(){}render(){}dispose(){}};
for(const name of ['models/anatomy-data.js','models/skin-data.js','experience.js'])vm.runInContext(fs.readFileSync(name,'utf8'),context);
const api=context.window.INSIDE_DEFENSE;assert.ok(api,'3D initializes');assert.equal(api.content.length,6);assert.equal(api.raw.children.length,255);assert.equal(api.skin.children.length,1);const T=context.window.THREE;const bounds=new T.Box3().setFromObject(api.skin),size=bounds.getSize(new T.Vector3());assert.ok(Math.abs(size.y-4.8)<.001);assert.ok(size.x>1.7&&size.x<2.1);let triangles=0;api.raw.traverse(o=>{if(o.isMesh){const p=o.geometry.attributes.position;for(const n of p.array)assert.ok(Number.isFinite(n));triangles+=o.geometry.index.count/3}});assert.ok(triangles>50000);
function step(){now+=2200;const queued=callbacks;callbacks=[];for(const f of queued)f(now)}step();
for(let i=0;i<6;i++){api.go(i);step();assert.equal(api.getState().chapter,i);for(let j=0;j<3;j++){api.selectTopic(j);step();assert.equal(api.getState().topic,j);assert.equal(api.getState().activeMode,api.content[i].topics[j][3]);assert.ok(el('detail').textContent.length>60);assert.ok(el('title').innerHTML)}}api.go(99);step();assert.equal(api.getState().chapter,5);api.go(-1);step();assert.equal(api.getState().chapter,0);
assert.equal(el('error').textContent,'');const html=fs.readFileSync('index.html','utf8');for(const match of html.matchAll(/<script src="([^"]+)"/g))assert.ok(fs.existsSync(match[1]));assert.ok(!html.includes('type="module"'));assert.ok(!html.includes('cdn.'));console.log(`PASS: 6 chapters, all topic transitions, 255 anatomy meshes (${triangles} triangles), real skin alignment, local offline assets.`);
